#!/bin/sh
# Copyright (c) 2017 Greg Reagle
# 
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Allow editor to be used in a pipeline or as a pager.  The -v option is
# for viewing only (no further output) the end of a pipeline, so that you
# can use your favorite editor as a pager.  The editor is taken from VISUAL
# if defined, else EDITOR if defined, else /usr/bin/editor if there.  This
# program was inspired by vipe of moreutils.

# Examples:
# ls | edit-pipe | sort -r
# man mv | edit-pipe -v

tf=$(mktemp) || { printf '%s\n' "$0: cannot create temp file"; exit 1; }

if test -n "$VISUAL"; then edit="$VISUAL"
elif test -n "$EDITOR"; then edit="$EDITOR"
elif test -x /usr/bin/editor; then edit=/usr/bin/editor
else printf '%s\n' "$0: no editor defined"; exit 1
fi

cat > "$tf"
$edit "$tf" < /dev/tty  > /dev/tty
test "-v" = "$1" || cat "$tf"
rm "$tf"
